### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by Raina-M** [ruqianl/sgcocaller#2]
Hello, I tried to use `sgcocaller v0.3.7` to detect COs in gametes using scRNA sequences from pollens, and our reference genome was phased. Here is the command I ran:
```
dir_to_sgcocaller/bin/sgcocaller xo --threads 8 --cmPmb 1 --phased merged.bam informative_SNPs.recode.vcf cb.list myprefix
```
Then I got an error as follows:
```
{"<barcodeFile>": cb.list, "<BAM>": merged.bam, "--binSize": 2000, "<referenceVCF>": nil, "phase": false, "--lookBeyondSnps": 25, "--thetaREF": 0.1, "--outvcf": false, "--baseq": 13, "--minMAPQ": 20, "--threads": 8, "--stepSize": 200, "--cmPmb": 1, "--chrom": nil, "--minPositiveSwitchScores": 8, "--minSwitchScore": 50.0, "<VCF>": informative_SNPs.recode.vcf, "<gtMtxFile>": nil, "--barcodeTag": CB, "<phasedSnpAnnotFile>": nil, "sxo": false, "--maxExpand": 1000, "--maxTotalDP": 25, "xo": true, "--phased": true, "--templateCell": -1, "--help": false, "<SNPPhaseFile>": nil, "--maxDP": 5, "--minDP": 1, "--minTotalDP": 10, "--maxDissim": 0.0099, "swphase": false, "--posteriorProbMin": 0.99, "--minSNPdepth": 1, "--thetaALT": 0.9, "<out_prefix>": rbrevi_test, "<phaseOutputPrefix>": nil}
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
The error message looks like from Nim, which I am not quite familiar with. Can you give me a clue about how to solve this?

**Comment by ruqianl** [comment]
Hi, I guess it is because it didn't find the input files at the given path? and I found if the output prefix contain dirs like a/b/prefix, when the sub directories don't exist it throws error like that. Perhaps if you could share your files with me and I can have a closer look? Best,RL-------- Original message --------From: Meng Zhang ***@***.***>Date: Thu, Jul 21, 2022, 02:01To: ruqianl/sgcocaller ***@***.***>Cc: Subscribed ***@***.***>Subject: [ruqianl/sgcocaller] SIGSEGV: Illegal storage access. (Attempt to read from nil?) (Issue #2)
Hello, I tried to use sgcocaller v0.3.7 to detect COs in gametes using scRNA sequences from pollens, and our reference genome was phased. Here is the command I ran:
dir_to_sgcocaller/bin/sgcocaller xo --threads 8 --cmPmb 1 --phased merged.bam informative_SNPs.recode.vcf cb.list myprefix

Then I got an error as follows:
{"<barcodeFile>": cb.list, "<BAM>": merged.bam, "--binSize": 2000, "<referenceVCF>": nil, "phase": false, "--lookBeyondSnps": 25, "--thetaREF": 0.1, "--outvcf": false, "--baseq": 13, "--minMAPQ": 20, "--threads": 8, "--stepSize": 200, "--cmPmb": 1, "--chrom": nil, "--minPositiveSwitchScores": 8, "--minSwitchScore": 50.0, "<VCF>": informative_SNPs.recode.vcf, "<gtMtxFile>": nil, "--barcodeTag": CB, "<phasedSnpAnnotFile>": nil, "sxo": false, "--maxExpand": 1000, "--maxTotalDP": 25, "xo": true, "--phased": true, "--templateCell": -1, "--help": false, "<SNPPhaseFile>": nil, "--maxDP": 5, "--minDP": 1, "--minTotalDP": 10, "--maxDissim": 0.0099, "swphase": false, "--posteriorProbMin": 0.99, "--minSNPdepth": 1, "--thetaALT": 0.9, "<out_prefix>": rbrevi_test, "<phaseOutputPrefix>": nil}
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

The error message looks like from Nim, which I am not quite familiar with. Can you give me a clue about how to solve this?

**Comment by Raina-M** [comment]
Hello,
Thank you for the response, but I am sure that files and directories are accessible. I will send you some test data I currently use.

**Comment by cheesemania** [comment]
Hi, I'm very interested in using this tool. I also get an identical issue to this, using 0.3.9. I tried installing prior versions (0.3.6, 0.3.4 and 0.3.3) all using conda. 

./sgcocaller xo \
> --phased \
> --cmPmb 0.0001 \
> possorted_genome_bam.bam \
> Cross.filt.recal.vcf \
> barcodes.tsv \
> BULK_1_sgco
2022-11-02T12:41:15-05:00{"<barcodeFile>": barcodes.tsv, "<BAM>": possorted_genome_bam.bam, "--binSize": 2000, "--dissimThresh": 0.0099, "--notSortMtx": false, "<referenceVCF>": nil, "phase": false, "--lookBeyondSnps": 25, "--thetaREF": 0.1, "--outvcf": false, "--baseq": 13, "--minMAPQ": 20, "--threads": 4, "--stepSize": 200, "--cmPmb": 0.0001, "--chrom": nil, "--minPositiveSwitchScores": 8, "--minSwitchScore": 50.0, "<VCF>": Cross.filt.recal.vcf, "<gtMtxFile>": nil, "--barcodeTag": CB, "--maxUseNcells": nil, "<phasedSnpAnnotFile>": nil, "--maxExpand": 1000, "sxo": false, "autophase": false, "--maxTotalDP": 25, "xo": true, "--batchSize": nil, "--phased": true, "--templateCell": -1, "--help": false, "<SNPPhaseFile>": nil, "--maxDP": 5, "--minDP": 1, "--minTotalDP": 10, "--maxDissim": 0.0099, "swphase": false, "--posteriorProbMin": 0.99, "--minSNPdepth": 1, "--thetaALT": 0.9, "<out_prefix>": BULK_1_sgco, "<phaseOutputPrefix>": nil}
2022-11-02T12:41:15-05:00 running sgcocaller 0.3.9
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

I installed on both a linux cluster, and a WSL version of Ubuntu locally and get the same issue. File path does not appear to be the issue for me

I then tried installing from source though ran into an error here also:

nimble install https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git
Downloading https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git using git
  Verifying dependencies for sgcocaller@0.3.5
      Info: Dependency on docopt@any version already satisfied
  Verifying dependencies for docopt@0.7.0
      Info: Dependency on regex@>= 0.11.1 already satisfied
  Verifying dependencies for regex@0.20.0
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.10.0
      Info: Dependency on hts@>= 0.3.4 already satisfied
  Verifying dependencies for hts@0.3.23
      Info: Dependency on https://github.com/ruqianl/distributions.git@any version already satisfied
  Verifying dependencies for distributions@0.1.0
 Installing sgcocaller@0.3.5
   Building sgcocaller/sgcocaller using c backend
    Prompt: Build failed for 'https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git@0.3.9', would you like to try installing 'https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git@#head' (latest unstable)? [y/N]
    Answer:
       Tip: 12 messages have been suppressed, use --verbose to show them.
     Error: Aborting installation due to build failure
ianc@PC51:~$ nimble install https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git --verbose
Downloading https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git using git
    Cloning latest tagged version: v0.3.9
       Info /tmp/nimble_1192/gitlabsvieduau_biocellgenpublicsgcocallergit/sgcocaller_1192.nims(5, 22) Warning: imported and not used: 'strutils' [UnusedImport]
  Verifying dependencies for sgcocaller@0.3.5
    Reading official package list
   Checking for docopt@any version
      Info: Dependency on docopt@any version already satisfied
  Verifying dependencies for docopt@0.7.0
    Reading official package list
   Checking for regex@>= 0.11.1
      Info: Dependency on regex@>= 0.11.1 already satisfied
  Verifying dependencies for regex@0.20.0
    Reading official package list
   Checking for unicodedb@>= 0.7.2
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.10.0
    Reading official package list
   Checking for hts@>= 0.3.4
      Info: Dependency on hts@>= 0.3.4 already satisfied
  Verifying dependencies for hts@0.3.23
    Reading official package list
   Checking for https://github.com/ruqianl/distributions.git@any version
      Info: Dependency on https://github.com/ruqianl/distributions.git@any version already satisfied
  Verifying dependencies for distributions@0.1.0
 Installing sgcocaller@0.3.5
   Building sgcocaller/sgcocaller using c backend
    Prompt: Build failed for 'https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git@0.3.9', would you like to try installing 'https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git@#head' (latest unstable)? [y/N]
    Answer: y
Downloading https://gitlab.svi.edu.au/biocellgen-public/sgcocaller.git using git
       Info /tmp/nimble_1192/gitlabsvieduau_biocellgenpublicsgcocallergit_#head/sgcocaller_1192.nims(5, 22) Warning: imported and not used: 'strutils' [UnusedImport]
  Verifying dependencies for sgcocaller@#head
    Reading official package list
   Checking for docopt@any version
      Info: Dependency on docopt@any version already satisfied
  Verifying dependencies for docopt@0.7.0
    Reading official package list
   Checking for regex@>= 0.11.1
      Info: Dependency on regex@>= 0.11.1 already satisfied
  Verifying dependencies for regex@0.20.0
    Reading official package list
   Checking for unicodedb@>= 0.7.2
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.10.0
    Reading official package list
   Checking for hts@>= 0.3.4
      Info: Dependency on hts@>= 0.3.4 already satisfied
  Verifying dependencies for hts@0.3.23
    Reading official package list
   Checking for https://github.com/ruqianl/distributions.git@any version
      Info: Dependency on https://github.com/ruqianl/distributions.git@any version already satisfied
  Verifying dependencies for distributions@0.1.0
 Installing sgcocaller@#head
   Building sgcocaller/sgcocaller using c backend
     Error: Build failed for package: sgcocaller
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/usr/bin/nim" c --noNimblePath -d:NimblePkgVersion=0.3.5 -d:release --path:"/home/ianc/.nimble/pkgs/docopt-0.7.0"  --path:"/home/ianc/.nimble/pkgs/regex-0.20.0"  --path:"/home/ianc/.nimble/pkgs/unicodedb-0.10.0"  --path:"/home/ianc/.nimble/pkgs/hts-0.3.23"  --path:"/home/ianc/.nimble/pkgs/distributions-0.1.0"  -o:"/tmp/nimble_1192/gitlabsvieduau_biocellgenpublicsgcocallergit_#head/sgcocaller" "/tmp/nimble_1192/gitlabsvieduau_biocellgenpublicsgcocallergit_#head/src/sgcocaller.nim"
        ... Output: Hint: used config file '/etc/nim/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: widestrs [Processing]
        ... Hint: io [Processing]
        ... Hint: sgcocaller [Processing]
        ... Hint: os [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: macros [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: pathnorm [Processing]
        ... Hint: osseps [Processing]
        ... Hint: posix [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: docopt [Processing]
        ... Hint: regex [Processing]
        ... Hint: tables [Processing]
        ... Hint: hashes [Processing]
        ... Hint: sequtils [Processing]
        ... Hint: types [Processing]
        ... Hint: sets [Processing]
        ... Hint: properties [Processing]
        ... Hint: properties_data [Processing]
        ... Hint: common [Processing]
        ... Hint: compiler [Processing]
        ... Hint: parser [Processing]
        ... Hint: exptype [Processing]
        ... Hint: scanner [Processing]
        ... Hint: exptransformation [Processing]
        ... Hint: nfatype [Processing]
        ... Hint: litopt [Processing]
        ... Hint: nodematch [Processing]
        ... Hint: types [Processing]
        ... Hint: types_data [Processing]
        ... Hint: nfa [Processing]
        ... Hint: deques [Processing]
        ... Hint: nfafindall [Processing]
        ... Hint: nfamatch [Processing]
        ... Hint: util [Processing]
        ... Hint: hts [Processing]
        ... Hint: utils [Processing]
        ... Hint: hts_concat [Processing]
        ... /home/ianc/.nimble/pkgs/hts-0.3.23/hts/private/hts_concat.nim(127, 9) Error: undeclared identifier: 'csize_t'
